### ISSUE TITLE
missing rich library

### ISSUE THREAD

**Issue by stevensu1977** [nus-apr/auto-code-rover#30]
missing rich library , when I use pip install rich in container, it's solved . 

PYTHONPATH=. python app/main.py swe-bench --model gpt-4-0125-preview --setup-map ../SWE-bench/setup_result/setup_map.json --tasks-map ../SWE-bench/setup_result/tasks_map.json --output-dir output --task django__django-11133
Traceback (most recent call last):
  File "/opt/auto-code-rover/app/main.py", line 16, in <module>
    from app import globals, globals_mut, inference, log
  File "/opt/auto-code-rover/app/inference.py", line 11, in <module>
    from app.api.manage import ProjectApiManager
  File "/opt/auto-code-rover/app/api/manage.py", line 12, in <module>
    from app import log
  File "/opt/auto-code-rover/app/log.py", line 5, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'
(auto-code-rover) root@aa1d1cf79120:/opt/auto-code-rover# pip install rich

**Comment by yuntongzhang** [comment]
Closing since fix has been merged.
