### ISSUE TITLE
Docker build: nvidia-cublas-cu12 version not found

### ISSUE THREAD

**Issue by happyherp** [nus-apr/auto-code-rover#70]
Hi, 

I am trying to install auto-code-rover on my iMac. 

I run 

```
docker build -f Dockerfile.scratch -t acr .
```

During the execution of `RUN conda env create -f environment.yml `, I get the error: 
````
#15 27.80 ERROR: Could not find a version that satisfies the requirement nvidia-cublas-cu12==12.1.3.1 (from versions: 0.0.1.dev5, 12.3.4.1, 12.4.2.65, 12.4.5.8, 12.5.2.13, 12.5.3.2, 12.6.0.22, 12.6.1.4, 12.6.3.3)
#15 27.80 ERROR: No matching distribution found for nvidia-cublas-cu12==12.1.3.1
```



I hope someone can help.

**Comment by Marti2203** [comment]
Hi, can you first try the Dockerfile.minimal ? This will not setup the requirements needed for executing SWE-bench tasks. Furthemore, the requirements.txt contains nvidia requirements for ollama, you can comment out the nvidia and ollama lines. I think that will allow to build a working conda environment.

**Comment by happyherp** [comment]
Thanks for the fast reply. 

When I run `docker build -f Dockerfile.minimal -t acr .`, the script fails at the exact same point. 

Afterwards I commented out this block from the requirements.txt
````
#nvidia-cublas-cu12==12.1.3.1
#nvidia-cuda-cupti-cu12==12.1.105
#nvidia-cuda-nvrtc-cu12==12.1.105
#nvidia-cuda-runtime-cu12==12.1.105
#nvidia-cudnn-cu12==8.9.2.26
#nvidia-cufft-cu12==11.0.2.54
#nvidia-curand-cu12==10.3.2.106
#nvidia-cusolver-cu12==11.4.5.107
#nvidia-cusparse-cu12==12.1.0.106
#nvidia-nccl-cu12==2.19.3
#nvidia-nvjitlink-cu12==12.4.99
#nvidia-nvtx-cu12==12.1.105
#ollama==0.3.3
````

Then I run `docker build -f Dockerfile.scratch -t acr .` again.
I get a different error this time:
```

#15 30.16 ERROR: Ignored the following versions that require a different python version: 0.21.0 Requires-Python <3.12,>=3.8; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.9.5 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.7
#15 30.16 ERROR: Could not find a version that satisfies the requirement triton==2.2.0 (from versions: none)
#15 30.16 ERROR: No matching distribution found for triton==2.2.0
```

I comment out `triton==2.2.0` as well and try again. After that the command finishes. 

After I start the container with `docker run -it -e OPENAI_KEY="${OPENAI_KEY:-OPENAI_API_KEY}" -p 3000:3000 -p 5001:5000 acr`. The container starts and I am in a shell. 
In the shell I run 
```
/opt/auto-code-rover# conda activate auto-code-rover
PYTHONPATH=. python app/main.py local-issue --output-dir output --model gpt-4o-2024-05-13 --model-temperature 0.2 --task-id task_1 --local-repo /opt/ai-shell-loop --issue-file /opt/ai-shell-loop-issue.txt

Traceback (most recent call last):
  File "/opt/auto-code-rover/app/main.py", line 17, in <module>
    from app import globals, globals_mut, inference, log
  File "/opt/auto-code-rover/app/inference.py", line 22, in <module>
    from app.model import common, ollama
  File "/opt/auto-code-rover/app/model/ollama.py", line 12, in <module>
    import ollama
ModuleNotFoundError: No module named 'ollama'
```

I put `ollama==0.3.3` back in the requirements.txt. Then I rebuild the image. 

This allowed me to start auto-code-rover in the container with 
````
conda activate auto-code-rover
PYTHONPATH=. python app/main.py local-issue --output-dir output --model gpt-4o-2024-05-13 --model-temperature 0.2 --task-id task_1 --local-repo /opt/ai-shell-loop --issue-file /opt/ai-shell-loop-issue.txt
```

**Comment by Marti2203** [comment]
Hi, awesome to hear that things are good! Will document this setup :)

**Comment by happyherp** [comment]
Thanks for your help.
